version: "3.9"

services:
  flask-app:
    build: .
    container_name: flask_service
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # port AMQP
      - "15672:15672"   # port UI

